name: Android and iOS Unit Testing

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  android-ios-unit-tests:
    name: Android Unit Tests and iOS Test Compile
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Make Gradle Executable
        run: chmod +x gradlew

      - name: Run Android Unit Testing
        run: ./gradlew androidApp:testDebugUnitTest --rerun-tasks --no-daemon

      - name: Compile iOS Unit Tests
        run: ./gradlew shared:compileTestKotlinIosSimulatorArm64 --rerun-tasks --no-daemon

      - name: Upload Unit Test Reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Android-iOS-Unit-Test-Reports
          path: |
            **/build/reports/**
            **/build/test-results/**
          if-no-files-found: warn
